### PR TITLE
fixed pointer cast that discards const qualifier

### PR DESCRIPTION
**Pull request by KeanBuyst**
`[]const Vector2` converted to `[*c]Vector2` which discards the const qualifier. Which throws an error.

I removed the const from `[]const Vector2` which fixed the issue. If you want to keep the `const` you can either use `@constCast`
or change `[*c]Vector2` to `[*c]const Vector2` and also change `cdef` counter part to also  `[*c]const Vector2` which may work. I haven't tested the last one.

There might be more functions also effected, but the ones I changed were the ones I located.

### CODE REVIEW

**Comment by Not-Nik** [comment]
I'd rather leave the `[] const Vector2`, but I don't have a testing project to try out if `[*c]const Vector2` works. I'll leave this open until I find some time.

**Comment by KeanBuyst** [comment]
I changed it to `[*c]const` and I tested it. No errors works just fine.

**Comment by Not-Nik** [comment]
Sorry, I didn't check what C does and since it doesn't make any const promises either, your first approach was correct

**Comment by KeanBuyst** [comment]
Ok no problem

**Pull request merged**
