### PR TITLE
Added audio examples. Fix bug in raylib textFormat.

### PR DESCRIPTION
**Pull request by ramonmeza**
Implemented raylib's (audio mixed processor example)[https://github.com/raysan5/raylib/blob/master/examples/audio/audio_mixed_processor.c]. 

I copied the audio files from raylib's repository and added them to this one under resources. Whenever someone gets around to implementing `zig build examples`, they will need to include that resources directory with the executable for this example to work properly.

Below is an image of the results of running `zig build mixed_processor`
image

### CODE REVIEW

**Comment by ramonmeza** [comment]
I compared to the original example. I have much more distortion. I will iron out these issues.

**Comment by ramonmeza** [comment]
I figured out there was a bug in raylib.zig. `textFormat` was switching on .Struct, which was throwing an error. I looked at some of the innards and found `@"struct"` is an alias for `Struct`, so I switched on that instead.

**Comment by ramonmeza** [comment]
All of the audio examples have been added. Here's the list

```sh
zig build mixed_processor
zig build module_playing
zig build music_stream
zig build raw_stream
zig build sound_loading
zig build sound_multi
zig build stream_effects
```

The only issues I notice:
- Allocation in `stream_effects` should instead pass the allocator as a parameter rather than hardcoding it in.
-  `stream_effects` seems to be slightly distorted when using LPF filter compared to native C build. Not sure why that is.

**Comment by Not-Nik** [comment]
This should be two PRs. One for the fix, one for the examples. Also take some time to read through [CONTRIBUTING.md](https://github.com/Not-Nik/raylib-zig/blob/devel/CONTRIBUTING.md).

`zig build examples` is implemented, so any build steps should work with this PR (should as in, you should make them work if they don't).

**Pull request closed without merging**
